### ISSUE TITLE
Generic Hydrator issue

### ISSUE THREAD

**Issue by juliangorge** [dbierer/oauth.unlikelysource.org#1]
Hello!
I've got this problem when I attach you AuthOAuth module to my Laminas Project:

Fatal error: Declaration of AuthOauth\Generic\Hydrator::extract($object) must be compatible with Laminas\Hydrator\ExtractionInterface::extract(object $object): array in /usr/local/var/www/module/AuthOauth/src/AuthOauth/Generic/Hydrator.php on line 20

**Comment by dbierer** [comment]
@juliangorge thanks for the notice.  I performed a Laminas migration on the source code. Everything seems to be working OK now.
